### ISSUE TITLE
指定した座標内から特定の色を探す関数の実装要望について

### ISSUE THREAD

**Issue by Patrick10731** [stuncloud/UWSCR#113]
## 要望
いつもお世話になっております。
このたびUWSCとUWSCRの画像の画像認識の仕様の違いにより同じ動作を行うことが困難になってしまっており、それを解決するための関数を考案したので投稿いたします。
UWSCRの画像認識はUWSCのchkimg並の速度と、chkimgXのあいまい画像検出技術を持ち合わせておりとても素晴らしいと感じております、そのためこの関数が実装された場合UWSCRの画像認識の使いやすさが格段に上がると考えています。
実装のご検討よろしくお願いいたします。

用途
UWSCRのChkimgがUWSCの仕様と異なり、画像の形が一致していると色違いに対しても真である判定を行ってしまうためこの関数を使用し、色に対してある程度厳格な判定をすることを目的とする
(色違いでも判定することはChkimgXでも見られる仕様のため、OpenCV自体の仕様である可能性が高い)
また現状のPeekColorでは検出された画像の位置や使うPCによって座標ごとの検出される色が異なるため、座標範囲を指定できるようにするのに加え、色幅を指定できるようにすることで認識精度を上げる
また画像認識をしなくとも、特徴的な色のある場所をクリックできるようにすることで、特定の色の文字をクリックしたりできるようにする

前提
PeekcolorやChkimgと同じく、Mouseorgを用いてのバックグラウンド判定ができるものとする

関数名
findcolor(仮)

処理

findcolor(R値, G値, B値, R許容範囲, G許容範囲, B許容範囲, 検索回数, x, y, x2, y2) 

R値,G値,B値
RGB値それぞれ単体の数値

R=$0～$FF
G=$0～$FF
B=$0～$FF
または0～255

許容範囲
数値がどれくらい離れているかを許容するか
例えばRの色指定$FFに対して色判定を行った場合、許容範囲$1なら$FEまで真とする
またRの許容範囲が$FFの場合R要素が発するすべての色に対して真と判定するものとする
これを利用し、色指定を$FF,$FF,$FF,$0,$0,$FF　とした場合RG値$FFFFが検出された場合B値の数値に関わらず真と判定できるものとする
同様に$FF,$FF,$FF,$2,$2,$2とした場合$FDFDFD、あるいは$FEFEFEでも真と判定できるものとする
G値だけで判定を行いたい場合も、G値に指定したい色を指定、R値、B値は何かしらの数値と、許容範囲値$FFを指定することで単体での判定も可能とする

R許容範囲=$0～$FF
G許容範囲=$0～$FF
B許容範囲=$0～$FF
または0～255

検索回数:Chkimgと同じ仕様

座標検索範囲 chkimgと同じくx y x2 y2を指定
Mouseorgでのバックグラウンド動作時は相対座標を指定
chkimgと同じく全画面から検索する場合、EMPTYと指定

戻り値
二次元配列
[x,y,見つかった色,ヒット回数]
x,y 一番最初に真と判定した座標
見つかった色：一番最初に真と判定した色のRGB値
ヒット回数:検索回数分検索をかけた結果、色が見つかった場合に該当座標範囲内にいくつ真と判定した色があったかの数値、実装は難しそうであればなくてもかまいません

Chkimgと同じく色が見つからなかった場合は空の二次元配列で返す

## 補足用コード

```stylus

findcolor(R値, G値, B値, R許容範囲, G許容範囲, B許容範囲, 検索回数, x, y, x2, y2)
```

**Comment by stuncloud** [comment]
> 画像の形が一致していると色違いに対しても真である判定を行ってしまう
> (色違いでも判定することはChkimgXでも見られる仕様のため、OpenCV自体の仕様である可能性が高い)

テンプレートマッチングについて調べると画像をグレースケール化するのが一般的なようなのでそれに倣っていましたが、実はopencvのテンプレートマッチングではグレースケール化する必要がなさそう？という話もあるのでchkimg改善の際にその調査もする予定です
グレースケール化が不要であればその問題も解消できるかもしれません

**Comment by Patrick10731** [comment]
回答ありがとうございます
とはいえ、今の色違いを判定する仕様も使える場面はあるのでグレースケール化が不要な場合においても、オプションでグレースケール化して判定するかどうかの選択制にしてもらえると助かります

**Comment by stuncloud** [comment]
![image](https://github.com/stuncloud/UWSCR/assets/2889508/c2c8ab59-d038-4e99-9bdc-b2f382fc481f)

```stylus
function bgr_array_to_int(arr: array)
    result = arr[0] * $10000 + arr[1] * $100 + arr[2]
fend

mouseorg(id)
offset_x = status(id, ST_X)
offset_y = status(id, ST_Y)
color = [0, 100, 0]
bgcolor = bgr_array_to_int(color)
threshold = [0, 5, 0]
// [0, 95, 0] から [0, 105, 0] を探索範囲とする
for found in chkclr(color, threshold)
    x = found[0] + offset_x
    y = found[1] + offset_y
    color = found[2]
    msg = "座標: <#x>, <#y> 色: <#color>"
    balloon(msg, x, y, FUKI_DOWN or FUKI_POINT, , , 0, bgcolor)
    if msgbox("次へ") = BTN_CANCEL then
        break
    endif
next
```

このような感じになります

加えて`chkimg`でグレースケール化しないオプションを指定できるようになりました
これにより色ではなく形の一致でマッチしてしまう問題を回避できます

**Comment by Patrick10731** [comment]
実装ありがとうございます！
希望通りの仕様です
v0.16の公開楽しみにしてます
