### ISSUE TITLE
Emptyの識別

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#138]
### 概要

If文で数値"0"がEmpty扱いされる。

### 再現スクリプト

```Stylus
A = 0; B = ""
If A = Empty Then MSGBOX("0=Empty") Else MSGBOX("0<>Empty")
If B <> Empty Then MSGBOX("<#DBL><#DBL> <> Empty") Else  MSGBOX("<#DBL><#DBL> = Empty")
```

### 再現手順

UWSCとＵWSCRでの実行結果は以下の通りです。
  UWSC           　　　UWSCR  
----------------   --------------------
0 <> Empty     0   =  Empty
""<> Empty     "" <> Empty

### バージョン

0.16.0

### 不具合発生環境

Windows 10

**Comment by stuncloud** [comment]
演算ではEMPTYを0扱いするが比較ではEMPTY以外とは等価としないようにする

似たようなケースで

```stylus
print EMPTY < 0
```

がUWSCではTRUEを返しUWSCRではFALSEを返すが、これに関しては**仕様とする**
これはUWSCの値がVARIANTであることに起因する
UWSCRでこれを再現するには以下の方法がある

```stylus
// UWSCR

// それぞれの値をVARIANTに変換する
vempty = vartype(EMPTY, VAR_EMPTY)
vzero = vartype(0, VAR_INTEGER)
// VARIANTでの比較ならUWSCと同等の結果になる
print vempty < vzero // True
```
