### ISSUE TITLE
""がUWSCと同じ働きをするようにして欲しい。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#139]
### 要望

UWSCRでは""とEmptyは厳格に区別されています。
Script:
Dim 空っぽ 
Dim 空文字 = ""
If 空っぽ = ""  Then MSGBOX("空っぽ  = <#DBL><#DBL>") Else  MSGBOX("空っぽ <><#DBL><#DBL>")
If 空っぽ = Empty Then MSGBOX("空っぽ = Empty") Else  MSGBOX("空っぽ <> Empty")
If 空文字 = ""  Then MSGBOX("空文字 = <#DBL><#DBL>") Else  MSGBOX("空文字 <> <#DBL><#DBL>")
If 空文字 = Empty Then MSGBOX("空文字 = Empty") Else  MSGBOX("空文字 <> Empty")

Ｒｕｎの結果：

   UWSC                     UWSCR
---------------------　　　-----------------------
空っぽ = ""          　 空っぽ <> ""　　　　　　<===
空っぽ = Empty    　 空っぽ  = Empty
空文字 = ""               空文字 = ""
空文字<>Empty       空文字<>Empty

しかしUWSCでは、空っぽでも空文字でも、どちらも""として扱えます。
変数を宣言した時点ではEmptyであるものが、何かが代入され、その後消去されると""になります。
即ちその変数はEmptyと""のどちらにでも成り得ますが、UWSCではそのどちらの状態も""で検出できました。
例えば、
For a = 0 to BBB
  If Idx[a] = "" Then CONTINUE
 　・・・・　
NEXT
ただこれはUWSCRでは
　If Idx[a] = "" Or Idx[a] =　Empty Then CONTINUE
とすれば、解決する事なので、無理にとは言いません。
現状の厳格論理キャラ路線で行くのなら、UWSCから移行する人の為にマニュアルに注意喚起の記述を入れておくのが望ましいと思います。

**Comment by stuncloud** [comment]
# 空文字とEMPTYを区別する理由

空文字とEMPTYを区別するのは例えばinputで

- 入力欄を空のままOKを押した場合空文字が返る
- キャンセルした場合EMPTYが返る

という仕様があり、これが区別できないのが問題になるからです

# UWSCの動作について

UWSCでは**EMPTYの変数とEMPTYまたは空文字を等価比較**するとTRUEを返すようです
かたや**リテラル表記の空文字とEMPTY**や先の例にもある**inputの戻り値としての空文字とEMPTY**の比較ではFALSEを返すという不整合が生じています

なぜこのようなことになっているのかは不明です
この仕様の由来に関する情報をお持ちでしたら教えてください

# UWSCRの方針

UWSCRでは変数もリテラルも関数の戻り値も区別がない(できない)ためこのような実装は難しいです
そもそも空文字とEMPTYの比較で場合により結果が異なることの方が問題であると考えています
よってこの件については現行の動作を仕様とします

# 質問

> 変数を宣言した時点ではEmptyであるものが、何かが代入され、その後消去されると""になります。

変数を消去というのがよくわかりません、UWSCにそのような方法があったのでしょうか？


> 厳格論理キャラ路線

どういうことでしょうか？

> UWSCから移行する人の為にマニュアルに注意喚起の記述を入れておくのが望ましいと思います。

善処します

しかし、あらゆる差分について予め記述しておくは難しいです
UWSCRの開発はUWSCの動作をベースにしていますが、作者の思い込みや勘違いで実装を異にする場合もありえますし、そもそも差異に気づけていなかったということもあります
例えば0と真偽値の比較など、自身では決して記述することのないコードなどは間違いに気づけません
プログラムの規模も想定を超えた大きさでもはや何を書いたか忘れている部分すら多々あります
そのような状況ですのである程度はご容赦ください

# お願い

再現コードをもう少し小さく書いていただけないでしょうか
結果についてももう少しわかりやすく記述していただけると助かります
今回であれば

```stylus
dim a
print a = "" // UWSC: True, UWSCR: False
```

このくらいで伝わります
よろしくお願いします

**Comment by DIYJii** [comment]
私の書き方が稚拙で、色々と手を煩わせてしまいました。

私は、戻り値の空文字とEmptyを一本化しろと言っているのでなく、「""」記号の役割を変えて欲しかったのです。
""とは本来、空文字を表す記号ですが、等価比較に於いては、その振る舞い方を変えて欲しいのです。
例えば　「If a = "" と書いた場合　a　が　空文字でもEmptyでもTrueを返して欲しい」というのが正確な表現でした。
他に、While, Repeat-Until, Select-Case　の場合も同様です。

INPUTの戻り値でキャンセルを押したかを調べたい場合は、上のような変更後も、先ずEmptyからチェックしてやれば問題は起きません。

　If 戻り値 = Empty Then 　　　//キャンセル
    ・・・・・
　ElseIf 戻り値 = "" Then 　　　//未入力
    ・・・・・
    Else　
　・・・・・

UWSCでの、この仕様の由来に関する情報は持ち合わせていません。
今迄私が書いたコードでは、Emptyと""の区別を必要とするケースは、コーディング・エラーを解析する場合以外は皆無でした。
しかし、Emptyや""の時は無処理とし、有意データの時のみ何らかの処理をすると言ったケースは頻繁に起きました。
という事でUWSCでは、論理的矛盾には目をつぶって、利便性の観点から、比較式での「""」は　空文字とEmptyの両方を意味する事にしたのではないかと推測します。

「変数を消去」というのは表現が間違っていました。　
ある変数が　Dim 指定後　Empty -> "xxx" -> "yyy" -> ""  等と変化する場合の事を言いたかったのです。

再現コードの件、そんなスマートな書き方は思い付きませんでした。心掛けます。

「厳格論理キャラ路線」の件、私の若い頃に似ているので、冗談を言ったまでです。失礼しました。

p.s.
UWSCの掲示板で見付けました。暇な時にでもどうぞ。

★　Inputの押されたボタンを判断する方法
https://www3.rocketbbs.com/13/bbs.cgi?id=umiumi&mode=pickup&no=430

★　加算演算子の連続について 
https://www3.rocketbbs.com/13/bbs.cgi?id=umiumi&mode=pickup&no=5064

**Comment by stuncloud** [comment]
要件は理解しましたが、この件に関しては要望にお応えできません

> INPUTの戻り値でキャンセルを押したかを調べたい場合は、上のような変更後も、先ずEmptyからチェックしてやれば問題は起きません。
> 
> 　If 戻り値 = Empty Then 　　　//キャンセル
> ・・・・・
> 　ElseIf 戻り値 = "" Then 　　　//未入力
> ・・・・・
> Else　
> 　・・・・・

残念ながらまさにこれが問題となります
空入力でキャンセル時の処理に分岐してしまいます

希望の動作を実現するには空文字とEMPTYが等価であるとするほかなく、この問題が不可避となります

> 「""」記号の役割を変えて欲しかったのです。

とおっしゃっていますがこれはUWSCRでは記号ではありません
長さ0文字列のリテラル表記となります
また `dim a = ""` とした場合の空文字を示す変数aとリテラル表記の空文字も区別されません
つまり変数とリテラル表記で実装を異なるものにするのも不可能なのです
(厳密に言えば実装が不可能ということはもちろんありませんが、言語の根幹となる仕様を大きく変える必要があるためおいそれとできない、という意味です)

そもそもこの件に関してはUWSCの実装がおかしいと考えています
UWSCRでは言語仕様の不備まで再現することはしません

**Comment by DIYJii** [comment]
キャンセルでの分岐がまさに問題との事ですが、１つのプログラムでINPUTを何か所も使うというのは、どんなアプリケーションですか？
私は今、アメリカのニュースサイトのスクレイピングみたいな事をしていまして、INPUTは検索語の入力用に一か所使っている
だけですので、キャンセルでの分岐は全く気になりません。それよりも、各サイトのHTMLが全然違うとか、記事によって取りたいデータが有ったり無かったりとか、千差万別のデータ処理を行う上で文字データ・エレメント次第で処理が分岐する箇所が非常に多く有り、その重要処理の部分での問題の多発で四苦八苦している次第。ＵWSCに無かった機能も早く使わせてもらいたいのですが、なかなかそこ迄行き着けません。

やっぱり、ダメですかね～？　ユーザー・フレンドリーで是非！

**Comment by technomodel** [comment]
inputだけではなくスクレイピングなどでも問題が生じると思いますよ。

`<p id="foo" data-bar="">baz</p>`

上記の要素をスクレイピングするとして以下を記述したとします。

```
a = tabs[0].document.querySelector("#bar") //存在しないid指定
b = tabs[0].document.querySelector("#foo").getAttribute("data-bar") //取得できたが結果は空文字
c = tabs[0].document.querySelector("#foo").getAttribute("data-baz") //存在しない属性指定
```

存在しないことと空文字が同一であると判定されるケースがあると困ることになりませんか。

現状のUWSCRだと

```
print a //EMPTY
print b //""
print c //EMPTY

print a = b //FALSE
print a = c //TRUE
print b = c //FALSE
```

と正しく判定されるので
「属性が存在しない事」を条件にしてif文などを記述できます。
もし `"" = EMPTY` となってしまうと
「属性が存在しない　または　存在するが空文字である」という条件に変わってしまうかと思います。

**Comment by stuncloud** [comment]
@DIYJii 
inputはあくまでも例です
`"" == EMPTY` という式が**状況により異なる結果を返すのは明らかにバグである**と申しております、このようなバグをあえて実装するのがユーザーフレンドリーとは思いません

空文字とEMPTYの両方を真としたい場合、僕なら`lengthu()`を使います
これならば空文字でもEMPTYでも0を返すからです
例としてinputを使います

```stylus
a = input(msg)

if lengthu(a) == 0 then
  // 空文字及びEMPTYの場合
  print "入力がありません"
else
  // 1文字以上の文字列
  print "<#a> が入力されました"
endif
```


たとえ仕様上可能だったとしても書くべきではないコードというのは存在します
今回の件は言わずもがなですが、先のissueにあった数値と真偽値の比較などもそうです
自身のスタイルというものがあるのも理解できますが、このような機会にそれを見直すのも良いのではないでしょうか

@technomodel 
現状`undefined`はEMPTYに変換されることがわかっています
`null`はNULLになります
それ以外にも値がないことを示すようなものがあればそれも仕様上EMPTYとなるはず…です (利用してるライブラリ依存なので実際にやってみないとわからない)
このあたりの話はドキュメントに記載がなかったかもしれないので書いておきます

**Comment by DIYJii** [comment]
はぁ～ 本物のスクレイピングとはそんな風にするのですか？？！！
⁯いいですねー、これこそ私の探していたToolです。

今迄の私のコードは、予め決めたサイトの情報を集める方式で、夫々のサイトのHTMLの構造を自分で分析して、
其れに合ったデータ収集の仕方をしていた為、新しくアクセスするサイトを増やすたびに、それ専用のコードを書かなくてはならず、何んとかそこを自動化したいと思っていた次第。

UWSCのサポート継続性のみならず、こういった新しい機能拡張性の欠如から、UWSCRへの移行を決断した事は正しかったようです。

ただ　議論の最初にInput関数を例に持って来たのは良く無かったですね。お互い、無駄な時間を使ったと思います。

将来性の為であれば、少々の不便は、我慢出来ます。 納得です。

You Won !

**Comment by DIYJii** [comment]
UWSCアプリのあちこちに散らばっているemptyや""が関係するスクリプトを一々拾ってUWSCR対応の変更をするより、
初期値をemptyにしなければエラーは起きないはず、との考えでDimやPublicで適当な値を予めSetしておく事にしました。
という事で、その作業を少し楽にする新しい関数の提案を、別途上げたいと思っていますので宜しく。

このissue#139については、私はこれでClose、OKです。お疲れ様でした。
