### ISSUE TITLE
存在しないファイルに対して　F_Readモード （F_Write無し)でFOPENを掛けると、戻り値-1ではなく、ファイルIOエラーになる。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#141]
### 要望

下のメッセージが出ます。
　
UWSCR : [ビルトイン関数エラー(FOPEN)] ファイルIOエラー (指定されたファイルが見つかりません。 (os error 2))

ちなみに、UWSCマニュアルには、「オープンできなかった場合は-1 を返す」と述べられています。

先ずF_EXISTSで調べれば、このエラーでこけてしまう事は避けられますので、無理にUWSCと同じスペックにして呉れとは言いません。ただ、UWSCからの移行者の為にも、少なくともマニュアルには、今ある戻り値ＩＤの内容の変更についての記述に、この変更点も加えて下さい。

**Comment by stuncloud** [comment]
`F_READ` のみで`fopen`した場合にUWSCのように無意味なfidを返したとして、どのみちそれでファイルを読み出すことはできないという理由から実行時エラーとすることを良しとした記憶があります。
ファイルオープン二失敗した場合にエラーが発生することドキュメントに明記しておきます

**Comment by stuncloud** [comment]
@DIYJii 
ドキュメントに反映した時点でクローズしても良かったですね
このissueに関してはこちらでクローズします

要望に関してはあまり明確なルールは設けていないのですが、こちらで解決したと判断した時点でクローズするか、issue作成者にこちらからクローズを依頼する感じですかね
とはいえここのところ新規issueが多く、未クローズの確認ができてなかったのでこんな風に確認していただけるのはありがたいです
