### ISSUE TITLE
文字列を行結合すると　"_<#CR>" やコメント　が余分に付いてくる。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#149]
### 概要

下の再現スクリプトを実行すると　"abcd"　となるべきところ
a_
b_
c_   //hoge
d
となる

### 再現スクリプト

```Stylus
x = "a_
b_
c_   //hoge
d" 
Print x
MSGBOX("Ok?")
```

### バージョン

1.0.0

### 不具合発生環境

Windows 10

**Comment by stuncloud** [comment]
#148 と同じ
