### ISSUE TITLE
FUKIDASI　：　指定通りのフォントサイズで表示しない。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#151]
### 概要

FUKIDASI：サイズ指定の数値に従って大きさは変わるものの、指定サイズより可成り小さい。

### バージョン

1.0.0

### 不具合発生環境

Windows 10

**Comment by stuncloud** [comment]
サイズ値をそのまま`CreateFontW`の`cheight`に渡していたのが問題
以下でサイズ値 (ポイント) をピクセルに変換する必要がある
また、cheightは負の数にする必要があった

```rust
unsafe fn point_to_pixel(point: i32) -> i32 {
    let hdc = Gdi::GetDC(None);
    let ppi = Gdi::GetDeviceCaps(hdc, Gdi::LOGPIXELSY);
    -(point * ppi / 72)
}
```

修正後の表示をメモ帳と比較 (Yu Gothic UI, 20)
![image](https://github.com/stuncloud/UWSCR/assets/2889508/1eb3deb6-c400-4c0f-846d-e93807107c1f)
