### ISSUE TITLE
ファイルをfcloseしなくても、fput や fdelline による変更は、即ファイルに反映されている。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#157]
### 概要

マニュアルの　fcloseの注意書きとして、

「ファイルを閉じない限り fput や fdelline による変更はファイルに反映されません」

と、UWSCと同じ仕様が書かれています。
しかし、実際にはfputやfdellineはfcloseを待たず即ファイルに反映されています。

下はfcloseされる以前に、実行時エラーでbreakしてしまうコードですが、それでも”fuga-2”がLine1に書き込まれたメモ帳　hoge.txt　がクリエイトされます。また、元々同名のファイルが存在する場合は、そこに、これ等の変更が加えられてしまいます。勿論、エラーは無く、只fclose無しでProgramuが正常終了する場合も同じ結果です。
ちなみに、UWSCでは、ファイルは作られない、あるいは、何も変更は加えられないという結果になります。

### 再現スクリプト

```Stylus
id = fopen("hoge.txt", f_read or f_write) 
  fput(id,"fuga-1",1)
  fput(id,"fuga-2",2)
  fdelline(id,1)
  piyo = "a"
  print piyo - 5
　fclose(id)　
```

### 再現手順

補足：
今の方式でも大量データ処理時のパフォーマンスが落ちないのなら、マニュアルの訂正だけでも良いのかなと思いますが、出来れば、UWSC方式も加えて実装し、fopenの引数でmode切り替えが出来るようにして貰えると有難いです。

アプリが何らかの問題でbreakするとか、強制終了されるケースに備えた、ファイル・リカバリーを考慮すると、不可逆性のアップデートがあるファイルとか、個々のデータ処理に時間が掛るファイルとか、夫々ファイルの特性によって、UWSC方式とUWSCR方式にメリット・デメリットが有りますので、両方の方式を実装して欲しいと思う次第です。

### バージョン

1.0.0

### 不具合発生環境

Windows 10

**Comment by stuncloud** [comment]
@DIYJii 
ファイルIDオブジェクトが破棄される際に自動でclose処理が行われるからです (デストラクタのような機能で実施されています)
よって

```stylus
fput(fopen(file, F_WRITE), "hoge")
```

といった記述を可能としています

> しかし、実際にはfputやfdellineはfcloseを待たず即ファイルに反映されています。

されていません
close処理が行われるまでファイルへの変更は行われず内部バッファのみが変更されているためです

とはいえ現状ほぼ確実にclose処理がいずこかで発生しているため変更を反映させないという選択が取れなくなっていて、これは問題ですね

> UWSC方式とUWSCR方式にメリット・デメリットが有りますので、両方の方式を実装して欲しいと思う次第です。

`F_AUTOCLOSE` (仮)のようなフラグを追加してこれを指定した場合のみ自動closeを有効にし、ない場合はfclose()を呼ばない限り変更が反映されないようにするという変更はどうでしょうか

```stylus
// 使用例
// 自動closeを利用したファイル変更
fput(fopen(file, F_WRITE or F_AUTOCLOSE), "hoge")
```

**Comment by DIYJii** [comment]
ユーザーからすると、マニュアルに書かれている事が全てですので、ああ云う結論になりました。悪しからず。

F_AUTOCLOSE 　大賛成です。

今、私が移行中のプログラムには、データ保全の為、クリック操作毎にfclose-fopenを掛けてdata saveさせている部分が有ります。F_AUTOCLOSEが出来れば、何事が有っても、最後にデータが保存される事が保証される為、fclose-fopenみたいな、非効率で、あほらしい事は、しないで済むようになります。
一方、別のファイルでは、不可逆的なUpdateを頻繁に行っていますが、ｆcloseを掛けない限り元のファイルには変更が加えられない事を前提に、万が一、クラシュしても、ファイルはそのままで、同じJobをReRunするだけでOKという建付けになっており、ここはF_AUTOCLOSE無しでという事になります。

F_AUTOCLOSE、是非それでお願いします。

**Comment by DIYJii** [comment]
ありがとうございます。👍
