### ISSUE TITLE
fopen などファイル操作のbusy状態についての質問

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#159]
### 質問

UWSCの時は、fopen,fget,fclose等と連続してファイル操作をすると、データが取得出来ない事が有り、Status(ID,ST_Busy)で聞いてやる必要が有ったのですが, UWSCRではどうなのでしょうか？ また、fclose,fopenの場合も、IDが一旦-1になるのを確認する必要が有るのでしょうか？

もしBusy確認等が必要なら、fopenの戻り値のIDの中に従来と同じWindowIDも加えて貰えると、楽なのですが。
Status関数には、今度UWSCRで新しく採用したIDは使えない為、別途GetIdでファイルパスから従来のIdを取得する必要が生じます。

### バージョン

1.0.0

### 実行環境

Windows 10

**Comment by stuncloud** [comment]
@DIYJii すいませんが質問の意味がわかりません

> UWSCの時は、fopen,fget,fclose等と連続してファイル操作をすると、データが取得出来ない事が有り、Status(ID,ST_Busy)で聞いてやる必要が有ったのですが, UWSCRではどうなのでしょうか？ また、fclose,fopenの場合も、IDが一旦-1になるのを確認する必要が有るのでしょうか？

ファイルIDに対して`status`を使う？？？
UWSCではそんなことが可能だったのですか？
つまりウィンドウIDとファイルIDは重複することがないといった仕様があったということですか？

```stylus
// UWSC
wid = getid(title)
fid = fopen(file)
print wid // 1
print fid // 2
```

こうなるということ？

UWSCRでは`fopen`に失敗する場合に実行時エラーとなるので、UWSCのように-1のまま続行するということはありません
また、UWSCRの`status`はウィンドウの状態を得るものとして実装されており、ファイルの状態を得る機能はありません

あえて質問に答えるなら、する必要はないがそもそもできない、となるでしょうか

> もしBusy確認等が必要なら、fopenの戻り値のIDの中に従来と同じWindowIDも加えて貰えると、楽なのですが。
Status関数には、今度UWSCRで新しく採用したIDは使えない為、別途GetIdでファイルパスから従来のIdを取得する必要が生じます。

？？？

`fopen`はファイルを開く関数でありウィンドウとはなんの関係もないのですが、何の話をされているのですか？
ファイルとウィンドウは全く異なるものなのですが、その区別はついていますか？

**Comment by stuncloud** [comment]
実際にUWSCで動作を確認したところ

```stylus
// UWSC
wid = getid(title)
fid = fopen(file)
print wid // 1
print fid // 1
```

やはりgetidとfopenはそれぞれでユニークなIDを持つので相関性はない

```stylus
// UWSC
fid = fopen(file)
print fid // 1
print status(fid, ST_BUSY) // FALSE
print status(fid, ST_PATH) // empty
```

ウィンドウID1が存在しないのでstatusは何も返さない
やはりファイルIDに対してstatusが動作するということはなさそう

**Comment by stuncloud** [comment]
# 参考：UWSCのID割り振り仕様

## ウィンドウID

`getid`に成功するたびにウィンドウに対してIDを割り振る、IDは1からインクリメンタルに割り振られる
`getid`の他に`getallwin`、`hndtoid`、`exec`などがID割り振りを行う

## ファイルID

`fopen`に成功するたびに開いたファイルにIDを割り振る
IDに対応するファイルが閉じられていない場合に`fopen`に成功すると、インクリメントされたIDが割り振られる
IDに対応するファイルが閉じられた場合そのIDは空番となり、その状態でfopenに成功するとそのIDが再利用される

```stylus
f1 = fopen(file1)
print f1 // 1
f2 = fopen(file2)
print f2 // 2
// id 1を閉じる
fclose(f1)
// id 1が再利用される
f3 = fopen(file3)
print f3 // 1
f4 = fopen(file4)
print f4 // 3
```

**Comment by DIYJii** [comment]
ヤ～、申し訳ない。私の不勉強で、WindowIDの事、完全に勘違いしてました。

言い訳の前に、fopen,fget,fclose・・について。

UWSCでは、間にSleep等のIdle時間を置かずfopen,fget,fcloseと連続して実行すると、たまにデータが取得出来ない事が有りました。
私のPCはHDDなのでアクセスに時間が掛る事と、UWSCは非同期プログラミングとの事なので、open完了を待たずしてfget、あるいは,
fget完了を待たずしてfcloseを掛けてしまって、データ取得が出来ないという現象が起きていたのだと推測し、それらのFileOpの
間に、BusyならWaitする事を期待したWaitLoopを後から入れたという訳です。

ですから、そもそも私の質問は、

「UWSCRのファイル処理は同期型プログラミングで良く、前の処理終了を確認せずにfopen,ｆget,fcloseを連続して書いてもOKか」という意味でした。

ここからは、言い訳：
 id = EXEC("notepad.exe C:\・・）で立ち上げたtxtファイルidがStatus等のウィンドウ関係の関数に正常に
働いていたので、てっきりウィンドウとファイルのIdが同一のものと勘違いしていました。ちなみに、EXCELも同じ振る舞いでした。
加えて、id = fopen(・・)の id を使ってStatusとSleepを使ったWait Loopもエラー無しで動いていますので・・
今からすれば、fopenで開いたtxtファイルには、何の役にも立たないLoopで、ただSleepで時間稼ぎして、
ファイル処理完了を待っていたつもりになっていたという事ですね。


色々、お手間を掛け、申し訳ありませんでした。

**Comment by stuncloud** [comment]
UWSCのファイル操作が非同期というのは初耳ですね

ともあれそういう内容でしたらUWSCRの組み込み関数は原則非同期ではないので手続き的に記述すればその通りに動作するはずです
UWSCRの実装ではfputもfgetも内部のバッファに対して行い、ファイルに触るのはopen時とclose時のみとなります
F_READがあればopen時にファイル内容をバッファに持ちます
F_WRITE系があればclose時に適切なエンコードに変換してファイルに書き込みます

**Comment by DIYJii** [comment]
分かりました。余計な事を書かなければ、良かったですね。
