### ISSUE TITLE
def_dllの直後に文が書けない

### ISSUE THREAD

**Issue by cocco84** [stuncloud/UWSCR#160]
### 概要

タイトルの通り
[#145](https://github.com/stuncloud/UWSCR/issues/145)に関連？ 

### 再現スクリプト

```Stylus
def_dll WSACleanup():long:ws2_32.dll
a = 1 //文と同じ行に別の文が記述されています
```

### バージョン

1.0.0

**Comment by cocco84** [comment]
コメントで行間を取れば回避可能
```
def_dll WSACleanup():long:ws2_32.dll
//
a = 1 
```

**Comment by stuncloud** [comment]
解析方法を見直したところ、予期せず半角スペース入りのdllパスにも対応できるようになりました :)
