### ISSUE TITLE
If 関数でのFalseの使い方に関する注意点のガイドを作りました。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#168]
### 要望

良かったら、校閲のうえ、マニュアルに載せて下さい。
[ガイド.txt](https://github.com/stuncloud/UWSCR/files/15369486/default.txt)

**Comment by stuncloud** [comment]
拒否します、このような文章はドキュメントに掲載できません

ちなみにですね、if関数と書かれていますが、ifは文です
さすがに文と関数の区別がつかないとは思っていませんでした
となると今まで僕があれこれ書いていた内容も理解できていない部分が多々あったのでしょうね、どうにも話の噛み合わなさというか違和感が拭いきれなかったのですがなんとなく腑に落ちました

このissueは却下してクローズします

**Comment by DIYJii** [comment]
校閲の上といってます。ユーザーより開発者の方が知識レベルが高いのは当たり前でしょ。
言葉尻ではなく、内容のどこが、却下の理由か分かりません。本筋に集中して下さい。
「この様な文章」でなく「このような内容」で返事をお願いします。
却下はそれで結構です。あなたの城ですから。

**Comment by stuncloud** [comment]
@DIYJii 

> 校閲の上といってます。ユーザーより開発者の方が知識レベルが高いのは当たり前でしょ。
言葉尻ではなく、内容のどこが、却下の理由か分かりません。本筋に集中して下さい。
「この様な文章」でなく「このような内容」で返事をお願いします。

そうですね、内容が悪すぎて載せるべき情報が何も無いという話であるのに「このような文章」と書いたことについてはよくなかったですね
適切に言葉尻を捉えていただきありがとうございます

## ドキュメントの前提

UWSCRのドキュメント (オンラインヘルプ) はUWSCRの仕様を明記しリファレンスガイドとして機能することを目的としています

ゆえにコーディング方法の解説や初学者向けの手引といった情報を掲載するような性質のものではありません
そのような情報が必要な場合は作者または第三者によって別の媒体でドキュメントが公開されることが望ましいと考えています

## 記載できない理由

頂いたテキストはいささか蛇足が過ぎる内容であるため上記の前提に背きます
また、不正確な部分や不可解な記述も多く、そのような部分を省くと校閲すべき内容が残りませんでした

### 詳細

> If関数は、

ifは関数ではありません、誤情報となります

> UWSCとは異なって、単なるTrue/False でなく真偽性を評価できるようになった為

そもそもUWSCはifの条件式において真偽値、すなわちTRUEまたはFALSEを要求していません
UWSCでは式を評価した結果の値のVARIANT型をVT_R4 (倍精度浮動小数点数) に変換し、0と0以外で真偽を判定しています
これは変換に失敗した場合のエラーメッセージから読み取れる仕様です

UWSCの仕様の詳細まで記述する必要はないと思われるため記載はしません


> コーディング上、注意すべき点が有ります。

真偽判定および真偽性の評価についてはドキュメントに仕様が明記されています
そこから注意が必要になるかどうかはユーザー次第であり、これを記載するのは蛇足となると考えます


> =, <,>　あるいはPOS() 等を使った式の結果で、分岐の成否を決める場合には変更がありません。
しかし、真偽性評価では、文字列の場合、長さが0、又は"0"以外はTrueと判定される為、文字列の"False"はTrueとして扱われる事になります。
UWSC では、If "False" Then の場合、”False”は文字列であり、BooleanのTrue/Falseでは無い為、エラーとして検知されます。
しかし、UWSCRでは　If "False" Then　の　"False" は 文字列として認定されUWSCの様なエラーは起きずTrueと判定されます。


これらもドキュメントに仕様として明記してあるため蛇足です
このような差についてはUWSCに慣れたユーザーであれば、仕様の差異を読み取れます
UWSCに不慣れなユーザーであれば疑問にも思わない部分でしょう


> 但し、Ｉf  "False" = False Then の様に　等号を使った式では　"False"は　UWSC と　同様にFalseとして働き、式の結果は分岐成功となります。

これはUWSCの仕様をそのまま適用した結果です
条件式だけの話ではなく比較式としての仕様としてこれを再現しています
UWSCのこの仕様に関しては

- 文字列と真偽値の比較ではあえて真偽値を文字列にVARIANT型変換している
- VARIANTの比較関数の仕様で文字列と真偽値の比較は文字列比較となっている

のいずれなのかは不明です

この点に関しては比較式の仕様となり、条件式とは関係がないので記載の必要がありません
また、文字列と真偽値を比較するようなコードはよほどのことがなければ書いてはいけない類のものであり、そのようなものまで仕様を明記する必要性が感じられません

> 従って、コーディングの際、誤って"False"が　If "False" Then　として使われてしまうと、予想外の分岐が発生し、解析困難なトラブルに見舞われる可能性があります。

`Ｉf  "False" = False Then `からの流れでこの内容は不正です
先にも申したように`"False" = False`は比較式の話であり、条件式で問われるのはその評価結果である真偽値 (この場合`TRUE`) です

条件式において文字列が真であることはドキュメントに明記されているため、そこに関する情報としてはやはりこれも蛇足となります
また、コーディングの際誤って、というのはどのようなコードにも言えることであり、またドキュメントは前提に書いた通りコーディング指南書ではないためこのような注意書きも不要です

> 特に注意すべきアイテムとしては、
> １. PARAM_STR[]に入っているスクリプトの引数のTrue/Falseは文字列の"True/"False" (UWSCも同じ)
> 2. FPUTでCSVファイルに書き出された、True/Falseは、元がBoolean/文字列共に、ファイル上でもFGETで再読み込みされたものでも文字列の"True"/"False" (UWSCはBoolean->1/0)　
> 3. 配列に入っていたTrue/Falseは取り出してもそのままの形。但しそのエレメントをファイルに書き込むと文字列になってしまうので注意。
> 4. a = Split((true + "," + false),",")でa[]に入っているものは文字型の"True"/"False"　(文字列の","で繋ぐからTrue/Falseも文字列に変わる)

真偽性の評価とは関係のない話なので不要です

2についてはfputの仕様に関する話で、UWSCとの明確な差異となりますね
UWSCRではビルトイン関数の引数が文字列を受ける場合は受けた値を文字列に変換する仕様があります
その場合`TRUE`はTrue、`FALSE`はFalseという文字列に変換されるため、fputでもそのように書き込まれます
UWSCがどのような理由で真偽値を数値にしているかはわかりませんが、UWSCにおいてそれを期待していたコードであれば問題にはなりますね
これに関して気になるようであれば別途issueを発行してください

> If処理の方法としては

if処理の方法と書かれていますがif文では1のような処理は行っていません
if文を書く場合の指南という意味なのであれば、前提に書いた通りそのような記載は不要です

> 1. 文字列をBooleanに変換、または0/1に変換してから If a Then　にいれる。

コーディング方法についての記載なので不要です

2.　If a = True/False Then を使って、If a Then　は　使わない。

これはコーディングとしては悪い例となるので論外です
このようなコードを書いてはいけません

3. OPTION FORCEBOOL を使う。但しTrue/False以外はエラーとなるので、If POS(a,b) Then のような真偽性評価が使えなくなる。

仕様が明記してあるので不要です

## おまけ：真偽性評価の有効な使い方

真偽性の評価は確かに雑な仕様でありバグの温床でもありますが、場合によっては有用です

```stylus
function f(s: string = "")
    if s then
        print "<#s> が入力されました"
    else
        print "文字列の入力がありませんでした"
    endif
fend
```

このように引数`s`が文字列しか受け取らない場合、if文における変数`s`が有効な文字列を取りうるかどうかを簡潔に書き記すことができます
条件式の素性が明らかな場合はこのような書き方ができるのは便利です

要するに使い方の問題です
僕自身は真偽性評価の危険性について熟知していますし、それ故に`OPTION FORCEBOOL`を実装しました
`FORCEBOOL`を標準としないのは、UWSCRもUWSCと同じように雑になぐり書きできるスクリプト言語であってほしいという思いがあるからです

**Comment by DIYJii** [comment]
即ち、この世界には色々と素人には分からない、厳しい掟が有るという事ですな。

ところで、単純に真偽判定の「偽」に文字列の"False"も加えるのは問題ですかね？

**Comment by stuncloud** [comment]
@DIYJii 

> 単純に真偽判定の「偽」に文字列の"False"も加えるのは問題ですかね？

問題であると考えています
長さ1以上の文字列であるということを真とする中で、特定の文字列のみ偽とすることはできません

言語仕様でどうこうするものではありませんが、真偽値を示す文字列を真偽値として扱いたいのであれば`eval`関数がありますので、それを使っていただくのが良いかと思われます
これはUWSCでも有効なテクニックです

```stylus
b = "false"

if  eval(b) then
    print "bはtrue"
else
    print "bはfalse"
endif
```

`eval`の利点は、評価不能であれば実行時エラーになるので例えば `b = "hoge"` とした場合はエラーで弾けることですね
とはいえそれも`hoge`という変数などが存在しない限りは、という条件がありますから万能ではありません

ベストなのは条件式に渡す時点で変数が適切な値であることが保証されるようにコーディングすることです

**Comment by DIYJii** [comment]
なるほど。　evalは気付いてなかったです。これで、今迄、危惧していた事は防げそうです。
ただ、もっと早く言って欲しかった。お互い無駄なエネルギーを使わなくても済んだだろうと思われるだけに。
いずれにしても、長々と付き合ってくれて、有難う。
それでは、これで本当にCloseです。

**Comment by stuncloud** [comment]
@DIYJii 

> ただ、もっと早く言って欲しかった。お互い無駄なエネルギーを使わなくても済んだだろうと思われるだけに。

えええ…

evalについては #166 の最初の回答で書いて…ありますよね…？？？
同じことでも何度も書いてればいずれは通じるかもしれないと思って今回も書いたわけなんですが、さすがにその言い草はひどい

しかもevalについてはUWSCからあったものなので単にあなたの勉強不足でしょ、そこまで責任転嫁される筋合いないです

**Comment by DIYJii** [comment]
確かに、最初にeval言っておられますね。言い訳ですが、まだその時点でまだ、私から見ての問題点が
ピンポイントされてなかったので、見落としたのだと思います。大変失礼しました。
