### ISSUE TITLE
OPTION FORCEBOOL = true と指定しても　FORCEBOOL はSetされない。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#170]
### 概要

表題通り

Setするには「OPTION FORCEBOOL」のみを書くようにとの指示をもらったが、マニュアルには
それが　MUSTの書き方で、 「= True」 は書くな　とは、どこにも記述が無い

マニュアル　記述：

OPTION 設定名[=値]
値が真偽値指定の場合は省略可能で、省略時はtrueになります

OPTION FORCEBOOL[=bool]
TRUEにした場合if文やwhile, repeatの条件式がTRUEまたはFALSEしか受け付けなくなります

### バージョン

1.0.1

### 不具合発生環境

Windows 10

**Comment by stuncloud** [comment]
すでに対応済みです
時期リリースに含まれます

**Comment by stuncloud** [comment]
#167 と重複
