### ISSUE TITLE
「!」論理否定の使い方

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#175]
### 質問

変数　a が　""　又は数値にしか成らない条件の下、
式　If a = "" Then を　If ! a Then　に　置き換えてみたら
異なる結果になったのですが、この「!」の使い方は正しくないでしょうか？

私としては""の真偽性評価に対して論理否定しているイメージで使ったのですが、
UWSCRの建付けは、""以外の物全てを真偽性評価すると言う風になっているのでしょうか？

この使い方が誤りであればSyntax Errorにして貰えると良いのですが、
場合によって、正しいとも間違いとも言えるのですかね～？

### 補足用コード

```Stylus
a = ""
Print  a ?  "a = True" :  "a  =  False"     //　a  =  False
Print !a ?  "!a = True ":  "!a =  False"   //　!a  =  False
```

### バージョン

1.0.1

### 実行環境

Windows 10

**Comment by stuncloud** [comment]
実装を確認したところ真偽値、数値、EMPTY以外は一律falseにしていました
これは最初期に実装して以来手がついてない部分ですね…
現行仕様の一部はバグとし、仕様を整理して修正します

**Comment by stuncloud** [comment]
単に真偽性をひっくり返したのだと`CONDUWSC`だとかで不整合がありそうなので、`!` の右辺は `FORCEBOOL` や `CONDUWSC` の影響を受けるものとする

**Comment by stuncloud** [comment]
この修正により `! ""` は

- デフォルト: TRUE
- FORCEBOOL: エラー
- CONDUWSC: エラー

となります

**Comment by DIYJii** [comment]
聞いてみて、良かったです。
早い対応ありがとうございます。
