### ISSUE TITLE
メインルーティンの定義について

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#176]
### 質問

関数の後ろに書きさしのコードを置いておくと、それもがメインルーティンとしてスクリプト実行の対象となています。

UWSCでは

＜関数の定義＞
　※ 関数はメインルーチンの後に書いてください。
　　（メインルーチンは関数前までであり、関数後にメインルーチンを書いても実行されません）

となっていたのですが、UWSCRではその記述が見当たりません。UWSCRのスペックとしては、関数定義以外の部分に書いてあるコード全てをメインルーティンとして扱う事になっているのでしょうか？

私的には、未完のコードを実行して貰っては困りますし、エラーで引っ掛かるのは当然ですので、　//　でコメントアウトして問題回避していますが、出来ればUWSC方式にしてもらえると、有難いのですが。

### 補足用コード

```Stylus
Procedure hoge()
　fugo = "abc"
FEND
MSGBOX("Ok?")　　//UWSCR : Ok? 　   UWSC :
```

### バージョン

1.0.1

### 実行環境

Windows 10

**Comment by stuncloud** [comment]
> UWSCRのスペックとしては、関数定義以外の部分に書いてあるコード全てをメインルーティンとして扱う事になっているのでしょうか？

その通りです

関数定義等を書ける場所を制限することにメリットを見いだせなかったため、UWSCRではこの制限を撤廃しました
これは文頭に書かなければならなかったOPTIONにも当てはまり、どこに書いたとしても適切に処理されるようになっています

> 私的には、未完のコードを実行して貰っては困りますし、エラーで引っ掛かるのは当然ですので、　//　でコメントアウトして問題回避していますが、出来ればUWSC方式にしてもらえると、有難いのですが。

UWSCは関数定義以降に書いた手続きを実行しないようになってはいますが、それは実行されたくない手続きを関数定義以降に書いても良いという意味ではありません
(詳細は失念しましたが記述によっては未定義動作っぽい怪しい動きがあったはずで、わりと危ないという認識です)
そのような推奨されないコードに関しては**あえて**互換性を維持しない方針です

また、UWSCのような方式にするには構文解析及び評価処理を大きく変更する必要が生じ今となってはリスキーなので、このためだけに手を入れたくないという事情もあります

----

代替案となりますが、複数行をコメントアウトしたい場合は以下が有効です

```stylus
// 名前なしtextblockはコメント扱いとなる
textblock
print 1
print 2
print 3

print 4
print 5
print 6
endtextblock
```

**Comment by DIYJii** [comment]
解りました。textblockを使うようにします。
「構文解析及び評価処理を大きく変更する必要が生じ」
こんな、大変な事を要求している積りは微塵も無なかったものですから。済みませんでした。

**Comment by DIYJii** [comment]
解りましたので、こちらからCloseします。有難うございました。
