### ISSUE TITLE
zip()での圧縮ファイルのフルパス指定について

### ISSUE THREAD

**Issue by cocco84** [stuncloud/UWSCR#177]
### 要望

圧縮したい対象のファイルをフルパス指定した場合にディレクトリ構造ごと圧縮されてしまいます。
できればディレクトリは無視してファイルのみを圧縮するモードを実装していただけないでしょうか。

```
//スクリプトは c:\uwscr\zip.uws
doscmd("mkdir " + GET_CUR_DIR + "\foo")
fopen(GET_CUR_DIR + "\foo\hoge.txt", F_WRITE)

doscmd("mkdir " + GET_CUR_DIR + "\bar")
fopen(GET_CUR_DIR + "\bar\fuga.txt", F_WRITE)

files = [GET_CUR_DIR + "\foo\hoge.txt", GET_CUR_DIR + "\bar\fuga.txt"]
zip("piyo.zip", files)
```
上記で作成したzipファイルの構造は以下となりました。

```
piyo.zip
    +-- C_
         +-- uwscr
               +-- foo
                    +-- hoge.txt
               +-- bar
                    +-- fuga.txt
```
例えばPowerShellで
`compress-archive C:\uwscr\bar\piyo.txt, C:\uwscr\foo\hoge.txt C:\uwscr\piyo.zip`
とした場合のzipファイル構造は以下となります。

```
piyo.zip
    +-- hoge.txt
    +-- fuga.txt
```

`zip()`の引数の都合上オプション指定は難しいかも知れないのですがご検討いただけますと幸いです。

**Comment by stuncloud** [comment]
なるほど、確かにこのようなケースでディレクトリ構成はいらないですよね

ファイルが指定された場合はファイルだけ、フォルダが指定されればその中のフォルダ構成を維持といった感じにできたら良いのかな？現状zip関数の実装がライブラリ任せなので、細かく制御できるか確認してみます

引数に定数等でオプションを取る場合はslctbox方式であれば実現可能ですね
(第二引数が数値だったらオプション扱いにする、みたいな実装)
必要であればオプションにすることも検討します

**Comment by stuncloud** [comment]
https://github.com/stuncloud/UWSCR/blob/master/evaluator%2Fsrc%2Fbuiltins%2Ffile_control.rs#L502-L502

引数で受けたパスをそのままここに渡すのでzip内でそのディレクトリ構成ができてしまうっぽい

とはいえドキュメントのサンプルの書き方もやりたい

どうしようかな

**Comment by stuncloud** [comment]
PowerShellの`Compress-Archive`に合わせた

- 指定パスがファイルの場合はそのファイル名でzipに格納する
    - `hoge.txt` → `hoge.txt`
    - `C:\hoge\hoge.txt` → `hoge.txt`
- 指定パスがフォルダの場合はそのフォルダ以下のファイルすべてをフォルダを起点とした相対パスでzipに格納する
    - `hoge` → `hoge\hoge.txt`
    - `C:\hoge` → `hoge\hoge.txt`
