### ISSUE TITLE
複数行if文のマルチステートメントについて。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#183]
### 種別

質問

### 対象ページ

スクリプト構文

### 報告内容

マニュアルに、複数行ifで始まる文をマルチステートメント形式で書く事が出来る旨の記述が無い。

UWSC経験者にとっては、

＜マルチステートメント＞
　;　（セミコロン）　　　//　N88Basic的な１行ＩＦ文での使い方はダメ

との呪文が掛かっていますので、　言ってもらわないと折角のUWSCRでの改善が、使われず終いになってしまいます。

**Comment by stuncloud** [comment]
サンプルにif文も追加します

仕様上できるというだけで改善という認識は皆無でした

@DIYJii さんが書けることに気づいたということは

> 呪文が掛かっていますので、　言ってもらわないと折角のUWSCRでの改善が、使われず終いになって

しまうことはすでに否定されてる気がするので、まあサンプルだけあれば呪文が掛かった人には通じるでしょう

----

僕としてはこの記述は**仕様的に書けるけど書くべきではない**部類の構文なので、書いてもらわないほうがありがたいかな…という気持ちはあります
なんならこの機能の存在が他の様々なユーザー補助機能の実装を妨げ大変な苦労を余儀なくされたことから恨みすらある :(

**Comment by DIYJii** [comment]
ユーザー目線では、UWSCの時は、メイン処理から外れる簡単なIf・・EndIf文は1行で書けた方がスッキリするのになーと思う事がよく有ったので、UWSCRでは改善されたと感じました。他にも、そんな人が居るだろうとの想いで書いた次第。
でも、解りました。偶然知った人は、使っても良いけど、at your own risk で使って下さいと云う物も有ると云う事ですね。

ついでに、If hoge Then の Then 無しでも正常に処理される事も其の類ですかね？

**Comment by stuncloud** [comment]
> hoge Then の Then 無しでも正常に処理される事も其の類ですかね？

そうですね
なんでUWSCは`then`を省略できたのかはわかりませんが、おかげでUWSCRではあえてそのような実装をすることになりました
`then`なしはもしかすると不具合が出るかもしれなくて怖いんですよね

**Comment by DIYJii** [comment]
そうですか、Then無しの件、実は私も気持ち悪りーと思っていました。
今の処、不都合が生じるケースは見付かっていませんけど、いずれにしろ節操の無い書き方だと感じています。
これは、流行らない方が良いですね。私は本題の方もこれでOKですので、そちらで,Closeして下さい。

**Comment by stuncloud** [comment]
@DIYJii 以下についてUWSCでは**ダメ**でUWSCRで動く具体例を教えて下さい
(そもそも**ダメ**というのがどういう状態になることなのかもわかりません)

> ＜マルチステートメント＞
　;　（セミコロン）　　　//　N88Basic的な１行ＩＦ文での使い方はダメ

**Comment by DIYJii** [comment]
＜マルチステートメント＞
この件は、UWSCマニュアルの＜マルチステートメント＞のセクションで、うにうにさんがその使い方をするのはダメと言っています。
ですから、単に今迄はそのような書き方はして来ませんでした。
以下が、お尋ねの一例になります。

a = 1
If a  Then ; print "a = True" ; print "a <> False" ;  Else ; Print "a =
False"; endif

UWSCでは
If行のマルチ宣言はNG と言ってきます
UWSCRでは
a = True
       a <> False
とPrint して呉れます。

素晴らしい! スクリプトの行数が減って、その構造が分かり易くなって助かります。


ついでに

a = 1
If a  ; print "a = True" ; print "a <> False" ;  Else ; Print "a = False";
endif

と、Then 無しでもOKなのですね。（何となく、ちょっと危ない気がしますが）
