### ISSUE TITLE
負のゼロについて

### ISSUE THREAD

**Issue by cocco84** [stuncloud/UWSCR#186]
### 種別

要追記

### 対象ページ

スクリプト構文

### 報告内容

UWSCには負のゼロが存在しないようなのですが、UWSCRでは扱いがあると思われますので
ドキュメントに記載しておいたほうが混乱を招きにくいかなと思いました。

```
a = -0
print a                       //UWSCR -0 UWSC 0
print a + 0.0                 //UWSCR  0 UWSC 0

b = encode(a, CODE_BYTEARRAY)
print length(b)               //UWSCR  2 UWSC 1 
```

` round(-0.1, 0)`の結果を文字列として取り扱いするケースなどを想定しています。

**Comment by cocco84** [comment]
余談ですが以下の結果がUWSCと異なりました。
```
a = "abcde"
print length(encode(a, CODE_BYTEARRAY)) //UWSCR 5 UWSC 3

b = encode(a, CODE_BYTEARRAY)
print length(b)                         //UWSCR 5 UWSC 5
```
UWSC側が変なように思いますがお知らせしておきます。

**Comment by stuncloud** [comment]
負のゼロについてはドキュメントに記載します

追記の`CODE_BYTEARRAY`の件はUWSCのバグっぽいですけど、なぜそうなっているかが全く想像できないのが不気味ですね

**Comment by stuncloud** [comment]
@cocco84 スクリプト構文のページに数値についての項目を追加し、負のゼロについても記載しました
https://stuncloud.github.io/UWSCR/syntax/statement.html#id37
