### ISSUE TITLE
FCLOSEしていないのに、空のFileが作られる

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#188]
### 概要

F_Writeオンで、新規FileのFOPENをすると、FCLOSEを掛けないでプログラム終了しても
中身のない空のファイルが作られる。（F_AUTOCLOSEは指定していない）
FGET,　FPUTを全くしなくても、結果は同じ

### 再現スクリプト

```Stylus
//TestFile.txtが存在しない事を確認

ID = FOPEN("C:\Users\Public\Documents\TestFile.txt",  F_Write or F_Read)

//TestFile.txtが作られた事を確認
```

### バージョン

1.0.1

**Comment by stuncloud** [comment]
## 原因

`OpenOptions::create(true)`しているため
ファイルの新規作成が必要になる場合は`Fopen::close()`時にファイル作成と書き込みを行うようにすれば良いはず

## 対策

- 排他制御対応のためファイルすでに存在している場合は`Fopen::open`でopenしておく
- 新規作成時は`OpenOptions`を保持
    - この場合 `Fopen::close` が呼ばれたときに初めてcreateしopenする
- `Fopen::target` を追加、`Option<TargetFile>` (新設)を持つ

```rust
enum TargetFile {
    File(File),
    New(OpenOptions),
}
```

## その他

- `FILE_LIST` は多分不要なのでなくしてもいいはず、すると `Fopen::id` も不要
- `Fopen::close`で`Fopen::target`を`None`にする
- これでfidのコピーが作られても問題ないはず

**Comment by DIYJii** [comment]
超速の回答有難うございます。

**Comment by stuncloud** [comment]
## 変更
 
- 該当ファイルが存在しない場合はfopen時にファイルを作成しないようにした
    - この場合fclose時に初めてファイルを作成して書き込みを行う
