### ISSUE TITLE
スクリプトがパラメータ無しで起動された場合、PARAM_STR[ ]をアクセスするとエラーになる。

### ISSUE THREAD

**Issue by DIYJii** [stuncloud/UWSCR#189]
### 概要

スクリプトで起動時のパラメータを調べようとすると、無入力の場合以下のエラーになる。

WSCR実行時エラー
test.uws 1行目: Print PARAM_STR[ｘ]
[評価エラー] インデックスが範囲外です (ｘ)

パラメータ入力無しの場合はDefault適用という書き方も有るので、エラーにしない方が良いと思います。
ちなみに、UWSCではエラーとはならず、　Empty/"" が返されます。

### 回避方法

Para = Function(x)
    If  x <= Length(PARAM_STR) -1 Then RESULT = PARAM_STR[x] Else RESULT = Empty
 FEND

 Para(x)と書けばPARAM_STR[x]が取得出来ます。ｘが無入力パラメータを指す場合はEmptyが返ります。

### 備考

無名関数、なかなか良いじゃないですか!
最初は、普通の関数で書こうとしたのですが、PARAM_STRがPublicではないので直接アクセス出来ない事に気付き、ひょっとして無名関数ならOKかなと思ってトライしてみたら、そこら辺にあるLocal変数、何でも好きに出来るじゃないですか。普通の関数だと、引数渡しやPublic宣言やらで、アクセス出来るようにするのが面倒でしょうがなかったのが・・・これは良いわ！
それに、わざわざリスト上遠く離れた所にある関数の中身を確かめに行かなくても、すぐそばに居るし。コンパクトに作れるし。
ここら辺の便利さは、今のマニュアルでは判らないので、もっと宣伝した方が良いですよ。

### バージョン

1.0.1

**Comment by stuncloud** [comment]
パラメータがないときの`PARAM_STR`インデックス呼び出しはUWSCでもエラーになっていた記憶があり、UWSCで`PARAM_STR`を使う場合は必ず`length(PARAM_STR)`で有無を確認するようにしてたんですが今見るとEMPTYを返していますね…

`PARAM_STR`に限り範囲外ならEMPTYを返すようにします

## 対策

- `Object::ParamStr(ParamStr)` を追加
- `ParamStr`を新設

```rust
struct ParamStr(Vec<String>);
impl ParamStr {
    fn get(index: usize) -> Option<String> {
        todo!()
    }
}
```

- call対応も考える

**Comment by DIYJii** [comment]
超速の回答有難うございます。

**Comment by stuncloud** [comment]
インデックス外の場合EMPTYを返すようにする

```powershell
uwscr test1.uws 123
```

```stylus
// test1.uws
print PARAM_STR    // ["123"]
print PARAM_STR[0] // 123
print PARAM_STR[1] // EMPTY

call test2.uws(456)
```

```stylus
// test2.uws
print PARAM_STR    // ["456"]
print PARAM_STR[0] // 456
print PARAM_STR[1] // EMPTY
```
