### ISSUE TITLE
fopen(NULL)に対応する

### ISSUE THREAD

**Issue by stuncloud** [stuncloud/UWSCR#191]
#188 やるついでにやる
パスにNULLやEMPTYが渡されたら虚ファイルに対する読み書きが行えるようにする

**Comment by DIYJii** [comment]
:+1:良いですね！
保存する必要の無いワーク・ファイルをしょっちゅう使っていますので、これが出来たら助かります。

**Comment by stuncloud** [comment]
#188 の対応により`fopen(NULL)`も可能になった
ただし、fcloseするとUWSCとは異なりエラーになる (制限事項)
とはいえ用途的に**fcloseはしないはず**なので問題にはならないと思われる
あえてfcloseする場合は第二引数をTRUEにすることで回避可能

## この動作について

この動作は意図された機能ではなく仕様上このように動作してしまうというものであり、動作保証外とする
よってドキュメントにも記載しない
