### ISSUE TITLE
UObjectからキーと値を一覧で取り出したい

### ISSUE THREAD

**Issue by cocco84** [stuncloud/UWSCR#208]
### 概要

タイトルの通り

### 理由

こういうデータで日付のみ合致するかどうか判定したいです。
現状だとMatch()で配列にしたりしていますが不便を感じています。

```
{
    "2023-01-01": "元日",
    "2023-01-02": "休日 元日",
    "2023-01-09": "成人の日",
    "2023-02-11": "建国記念の日",
    "2023-02-23": "天皇誕生日"
}
```

### 実装例

```Stylus
obj = @{
	"foo": "1",
	"bar": "2"
}@

key   = obj.keys()   //[foo, bar]
value = obj.values() //[1, 2]
```

**Comment by stuncloud** [comment]
@cocco84 

`keys()`と`values()`メソッドを追加します

加えて

```json
{
    "foo bar": 1
}
```

といったjsonに対して

- `obj["foo bar"]`
- obj."foo bar" ( PowerShell方式、実装は難しいかも？

のようなアクセス方法がなにかしら必要なので、合わせて実装します

これがあれば`keys()`で得たキー名から値へのアクセスもしやすくなりますし

```stylus
for key in obj.keys()
    if validator( key ) then
        do_something( obj[ key ] )
    next
next
```

**Comment by stuncloud** [comment]
`obj[key]`での呼び出しは対応済みだった

**Comment by cocco84** [comment]
現状だと呼び出しは出来ても`obj[key]`だと変更ができないようなので、変更のご対応が可能ならして頂けると嬉しいです。

```
obj = @{"key":"val"}@
obj["key"] = 1 //代入エラー
```

**Comment by stuncloud** [comment]
@cocco84 代入は見落としてました
バグとして新規issueにしてもらえますか
