### ISSUE TITLE
createformを連続して使用するとハングアップする

### ISSUE THREAD

**Issue by cocco84** [stuncloud/UWSCR#216]
### 概要

createformで作成したhtmlファイルのsubmitをクリックし、
その後連続してcreateformが実行されるとハングアップします
（×で閉じた場合は問題が生じません）

### 再現スクリプト

```Stylus
a = createform("sample_1.html", "cf1") //submitをクリック
b = createform("sample_2.html", "cf2")
```

### 回避方法

```
a = createform("sample_1.html", "cf1") //submitをクリック
msgbox("aaa")
b = createform("sample_2.html", "cf2")
print a.data
print b.data
```

上記の場合はハングアップはしませんでした
ただしcreateformが優先されるようでmsgboxのOKボタンは押下できず、
2回目に実行したcreateformのsubmitをクリックまたは×でキャンセルすると
msgboxは消えます。

### 備考

同一のバグかどうかは判断がつかずこちらに記載しますが

```
a = createform("sample_1.html", "cf1") //submitをクリック
msgbox("aaa")
msgbox("bbb")
msgbox("ccc")
```

上記の場合でもmsgboxの挙動がおかしくなります

※aaaとbbbが同時に表示され、最初に実行されているaaaのOKボタンや×がクリックできない
※bbbのOKか×をクリックするとaaaも消失する

### バージョン

1.0.3

### 不具合発生環境

Windows 10

**Comment by stuncloud** [comment]
報告ありがとうございます
調査します

**Comment by stuncloud** [comment]
@cocco84 調査および対策を行いました、修正は次リリースに反映されます

## 再現スクリプトについて

ハングアップは再現しませんでしたが、二度目のcreateformが実行時エラーになりました
(こちらで再現できる現象が報告とは異なりますが、どのみちバグの原因を潰せばいずれも解消されるのではないかと思います)

```
UWSCR実行時エラー
test.uws 2行目: b = createform("sample_2.html", "cf2")
[Formエラー] webview2-com Error: TaskCanceled
[1120/140549.991:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1412
```

### 原因

submitされた際にメッセージループ内で自身に対し`DestroyWindow`を実行していたが、ウィンドウプロシージャにおいて`WM_DESTROY`受信時に`PostQuitMessage(0)`を送っていたため、自身ではなく次に出現するウィンドウ (のメッセージループ) が即終了していた

1. cf1のsubmit押下
2. cf1のメッセージループ内でWebView内でsubmitされたことを検知
3. cf1自身にDestroyWindow
4. cf1のウィンドウプロシージャでWM_DESTROYを受信しPostQuitMessage(0)を実行
5. ch2表示直後にそのメッセージループもPostQuitMessageにより終了するためエラーになる

### 対策

- createform
    - submit時に自身のwebviewを除去
    - WM_DESTROY受信時に自身のwebviewが存在するならそれを除去し、PostQuitMessage(0)を送信
- msgbox, input, slctbox
    - PostQuitMessageの送信元が自身のHWNDではなかった場合にメッセージループを抜けないようにした

## msgboxの動作異常について

### 回避方法に記載されたコード

msgboxが表示されたままcf2が表示されるのも上記の原因によるもので、msgboxのメッセージループがPostQuitMessageによる終了メッセージを受け取っていたため即座に終了し、次の処理に以降するためcf2が表示されていました
msgboxが操作できなかったのもそのためで、メッセージループがすでに終了しているため操作を受け付けていませんでした

### 備考のコード

これも同様のバグで、今回の対策により解消されます

**Comment by cocco84** [comment]
すみません、ハングアップはreplモードで実行した場合のみでした。
通常の実行はおっしゃる通りの挙動でした。
失礼しました。解決いただけたようでよかったです。

**Comment by stuncloud** [comment]
なるほどそうでしたか
後日replでの再現確認および対策が有効かどうかの確認もしておきます

**Comment by stuncloud** [comment]
- 現行バージョンのreplで二度目のcreateformがハングアップする現象を確認
- 対策版であればrepl上でもcreateformが正常動作することを確認

対策が有効だったようなのでハングする原因の調査まではしませんでした

次リリースはなるべく年内に出せるようにします
