### ISSUE TITLE
GetElementsByTagName は使えるのでしょうか？

### ISSUE THREAD

**Issue by kawamura1953** [stuncloud/UWSCR#51]
## chromeをUWSCRで操作しようとしています

print browser.document.url
print browser.url

はちゃんと動くのに、

for tag1 in browser.document.GetElementsByTagName(tg)

は動きません。

　UWSCR構文エラー
　[ブラウザ操作エラー] GetElementsByTagNameがありません

が画面に表示されます。

GetElementsByTagName　は使えないのでしょうか？

## 実行環境

- UWSCRバージョン: 8.0.1
- OS: Windows  10 Pro

**Comment by stuncloud** [comment]
エラーメッセージの通りです、GetElementsByTagNameは存在しません
使用可能なメソッドやプロパティについてはwikiの[ブラウザ操作](https://github.com/stuncloud/UWSCR/wiki/%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E6%93%8D%E4%BD%9C)をご確認ください

**Comment by stuncloud** [comment]
この質問が解決している場合はクローズしてください
そうでない場合はコメントしてください
