### ISSUE TITLE
一番最初の起動ができません。

### ISSUE THREAD

**Issue by kawamura1953** [stuncloud/UWSCR#53]
## 質問
「
     chrome = BrowserControl(BC_CHROME)
     exit
」
だけからなるプログラムをコマンドプロンプトから

    >uwscr.exe  xxx.uws

で実行すると、
chromeは立ち上がって、ブラウザの窓が出るのですが、
「
　1行目: chrome = BrowserControl(BC_CHROME)
　[HTTPリクエスト エラー] error sending request for url (http://localhost:9222/json/list): error trying to connect:
　 tcp connect error: 対象のコンピューターによって拒否されたため、接続できませんでした。 (os error 10061)
」
がコマンドプロンプトの窓に表示されます。
以後の実行はできません。

どうしてなのでしょうか？

## 実行環境

- UWSCRバージョン: 8.01
- OS: Windows 10

chrome  バージョン: 104.0.5112.102（Official Build） （64 ビット）

**Comment by stuncloud** [comment]
以下を試していただけますでしょうか

- ブラウザで `http://localhost:9222/json/list/` を開く
- PowerShellで `Invoke-RestMethod -Uri http://localhost:9222/json/list/` を実行する  

これらの場合でも同じエラーが表示されるかどうかを見ていただきたいです

- エラーが起きた場合
    - PowerShellで `Resolve-DnsName localhost` を実行する  
        結果に`127.0.0.1`が含まれているかどうか
    - PowerShellで `Get-NetTCPConnection -LocalPort 9222 | %{ps -Id $_.OwningProcess}` を実行する  
        結果に`chrome`が表示されるかどうか  
        ここでchromeが表示されない場合は

            1. 実行中のchromeをすべて終了する
            2. スクリプトを再実行する
 
        で改善するかどうか
- エラーが起きなかった場合
    - uwscr.exeの通信をファイアウォールで許可して改善するかどうか

**Comment by kawamura1953** [comment]
事前に chrome を手動で立ち上げて、画面にchromeの窓がある状態で、
uwscr での BrowserControl(BC_CHROME) を行うと
エラーになるみたいです。

**Comment by stuncloud** [comment]
その場合動作しないのは仕様です
事前にChromeが起動されている場合、デバッグポートを開けることができないためuwscrからの操作ができません
スクリプト実行前にChromeをすべて閉じておいてください
ただし、事前に`BrowserControl`関数で起動したChromeであれば再接続して操作できます

操作できないブラウザが起動している場合は`BrowserControl`関数がエラーを返すように修正する予定です

**Comment by stuncloud** [comment]
@kawamura1953  この質問が解決している場合はクローズしてください
そうでない場合はコメントしてください
