### ISSUE TITLE
タイトル  から  browser値  を得る方法は？

### ISSUE THREAD

**Issue by kawamura1953** [stuncloud/UWSCR#54]
既に開いてある複数のタブの タイトル を調べて
目的のタブ（１つ）に対応する browser の値を得たいのですが、
方法はあるのでしょうか？

 for tab browser1.gettabs()
   print 'title : ' + tab[0]
   print 'url   : ' + tab[1]
   print 'pageid: ' + tab[2]
   ifb pos( "hogehoge", tab[0] )
     browser = tab[3]
     break
   endif
 next

みたいな感じに書きたいのです。

もっとも、これらの記述って
　　　　browser　tab　element
の階層構造には合わないかな？

## 実行環境

- UWSCRバージョン: 0.8.1
- OS: Windows (10)

**Comment by stuncloud** [comment]
すいません、タブの切替機能がまだ実装されていません
しかし、`BrowserControl`関数の仕様的に

```stylus
for tab in browser1.gettabs()
    print 'title : ' + tab[0]
    print 'url : ' + tab[1]
    print 'pageid: ' + tab[2]
    ifb pos( "hogehoge", tab[0] )
        // 第2引数でタイトルまたはURLを指定することでそれにマッチするタブのオブジェクトを得られる
        browser = BrowserControl(BC_CHROME, tab[0])
        break
    endif
next
```
という書き方が (おそらく) できると思います

----

バージョン`0.11.0`でBrowserControl関連の大幅改修を予定しています
その中でタブの切替も実装しようと思います

- タブ切り替え機能 (browserオブジェクトはそのままに操作タブを変更する)
- getTabs()でタイトル等を含む配列ではなくブラウザオブジェクトを返すようにする (仕様変更)

のいずれかの方式で実装をしようと考えています
もし何か要望や実装案がありましたらご意見をいただけると嬉しいです

**Comment by stuncloud** [comment]
@kawamura1953  この質問が解決している場合はクローズしてください
そうでない場合はコメントしてください
