### ISSUE TITLE
エラー発生時の動きが変です

### ISSUE THREAD

**Issue by kawamura1953** [stuncloud/UWSCR#55]
ファイル　yyy.uws
  call .\zzz.uws
  print 333
  
  aaa("uuu")

  print 444
　
　
ファイル　zzz.uws
  procedure aaa(x)
   f1("vvv")
  fend
  
  procedure f1(x)
   g1(9)
  fend
　
　
のとき

　>uwscr.exe yyy.uws

を実行すると
  333
  2行目:   print 333
  [未定義エラー] 関数が未定義です (g1)

と表示されます。
print 333 の行を削除すると

  2行目:
  [評価エラー] 不正なエラー行指定 (6)

と表示されます。
どしてなのでしょうか？

## 実行環境

- UWSCRバージョン: 0.8.1
- OS: Windows (10)

**Comment by stuncloud** [comment]
call文が入るとエラー行のカウントがずれているのかもしれません
確認します

**Comment by stuncloud** [comment]
# 原因

Evaluatorがcallされた別ファイルを認識していないのが問題
本来のエラー発生箇所は `zzz.uws` の6行目
```stylus
g1(6)
```
> 2行目: print 333
[未定義エラー] 関数が未定義です (g1)

なぜ2行目のエラーとして表示されているかはよく調べてみないとわからない[^1]

> 2行目:
[評価エラー] 不正なエラー行指定 (6)

これについては `6行目のエラー` なのでメインスクリプト (`yyy.uws`) の6行目を取得しようとするが、
> print 333 の行を削除
してスクリプトが5行になっている為 `UErrorMessage::InvalidErrorLine` が発生している
しかしこちらもなんで2行目のエラーとして出力されてるのかは要調査[^1]

[^1]: この2行目問題は`call`文に起因するものと思われる
ast見るとcall行の情報がない、どうやって処理してんだっけ…

# 対策

Parserと同様にどのファイルのどの行か？がEvaluatorにわかるようにする必要がある

**Comment by stuncloud** [comment]
暫定対策としては、call先のスクリプトで実行時エラーが出ないようにしてもらう…くらいですかね…
ご不便をおかけしますがよろしくお願いします

**Comment by stuncloud** [comment]
> 2行目として表示される
call文は対象スクリプトに実行できる部分(グローバル定義以外)があればそれを関数として呼び出すが、今回のケースだとそれがないのがなにか影響してるのかも

**Comment by kawamura1953** [comment]
ファイル名　や　何行目か　は表示できなくても、せめて

　　　[未定義エラー] 関数が未定義です (g1)

のように、
未定義の関数名だけでも、表示してもらえると
助かるのですが
（難しいですかね）

**Comment by stuncloud** [comment]
「不正なエラー行指定」エラーは内部的な話なので本来出す必要はない(かつ通常は発生し得ないという想定)なので、これを出さずに元のエラー(g1がない)のままにすることは可能です
全体的な修整が困難(時間がかかりすぎる等)であれば0.9.0ではエラー行情報は諦めてエラーメッセージだけ正しいものを出す、という対応を取ります

**Comment by kawamura1953** [comment]
おまかせします。
よろしくお願いいたします。

**Comment by stuncloud** [comment]
0.9.0で対応
- 正しいエラーメッセージが表示されるようになります
- エラー発生行とその行番号に加えスクリプト名が表示されるようになります
