### ISSUE TITLE
print tag1.outerHTMl　が変です

### ISSUE THREAD

**Issue by kawamura1953** [stuncloud/UWSCR#56]
正常なエレメントtag1がすでにあるとき

   print tag1.outerHTML

は、うまく動くのに

   print tag1.outerHTMl
   print tag1.outerHTM

は、「NULL」が印刷されます。
どしてなのでしょうか？。

それと、
innerHTMLなどのプロパティの一覧は
どこにあるのでしょうか？

いろいろ質問して、申し訳ありません。
開発、大変でしょうけど、頑張ってください。

## 実行環境

- UWSCRバージョン: 0.8.1
- OS: Windows (10)

chrome バージョン: 104.0.5112.102（Official Build） （64 ビット）

**Comment by stuncloud** [comment]
> print tag1.outerHTMl
print tag1.outerHTM
> 
> は、「NULL」が印刷されます。
どしてなのでしょうか？。

前者は大文字小文字の不一致、後者は存在しないプロパティだからです

> innerHTMLなどのプロパティの一覧は
どこにあるのでしょうか？

ブラウザ上でエレメントが持つプロパティなので、基本的にはご自身で調べて頂く必要があります

- 開発者ツール (F12) で確認する
- 詳細を解説しているサイトを参照する ([MDN](https://developer.mozilla.org/ja/docs/Web)など)

----

UWSCR側でできるかもしれないこと、という仮定の話[^1]であれば

```stylus
// pseudo
properties = element.GetPropertyList()
print properties
```

のようなメソッドを追加することは不可能ではないとは思います
必要であればそのような要望を上げていただくのは構いません

[^1]: 念のため書いておきますが`GetPropertyList`というメソッドは存在していません、あくまで仮定の話です

**Comment by kawamura1953** [comment]
質問のしかたが間違いでした。

１．
   print tag1.outerHTML　は、うまくいくのに、
   print tag1.outerhtml　は、NULLになるのはなぜ？

以前の uwscでは、outerhtml　でうまくいきました。


２．
それと、
   print tag1.outerHTM
は、「NULLを印刷」でなく、「エラーで終了」の方が良いように思うのですが・・・

**Comment by stuncloud** [comment]
> 質問のしかたが間違いでした。
> 
> １． 
print tag1.outerHTML　は、うまくいくのに、 
print tag1.outerhtml　は、NULLになるのはなぜ？

ですから、大文字小文字が異なるからです
プロパティの取得はJavaScriptにより行われています
そのため大文字小文字が一致する必要があります

> 以前の uwscでは、outerhtml　でうまくいきました。

UWSC、Internet Explorer 及びCOMとは全く異なる機能です
そのため仕様も異なります

> ２． 
それと、 
print tag1.outerHTM は、
「NULLを印刷」でなく、「エラーで終了」の方が良いように思うのですが・・・

前述の通りJavaScriptによる値取得を行っており、`undefined`または`null`が返された場合はUWSCRはそれを`NULL`として扱います
ご指摘の状況では`undefined`が返されるため`NULL`になります

----

- 大文字小文字の区別をなくす
- 存在しないプロパティに対してはエラーを返す

これらは現状の仕様ではできませんが以下のような処理を施すことは不可能ではないと思います

1. エレメントのプロパティ一覧を取得
2. 与えられたプロパティ名と比較
    - 一致する→値を返す
        - 完全一致
        - 大文字小文字が異なるが一致するもの (複数ある場合はいずれか一つ)
    - 一致しない→エラーを返す

といった実装にすることで実現できるはずです

しかし、BrowserControlの設計思想というか目標が**ブラウザ上での操作をUWSCR上に持ち込む**なんですよね
大文字小文字を合わせることや`undefinded`が返れば`NULL`にするといったことはそれに則っています
UWSCRスクリプトの流儀からは離れてしましますが、普段JavaScriptに触れている人にとってはむしろ自然に使えるという点を重視しています

まとめると

- ご指摘されているような実装は不可能ではない
- しかし設計思想とは異なるためそのような実装はしない

というのが開発者側としてのスタンスです
もちろん利用者側として不服ということであれば要望を上げてもらうことは構いません
そのような意見が多いのであれば実装を検討します

**Comment by kawamura1953** [comment]
私は、JavaScript を使用したことがありません。

ただ、旧UWSCのプログラムが約300KB(80ファイル)ほどあるので、
これをできるだけ書き換えせずに chrome で動かしたいのです。

UWSCRの仕様に関してはお任せいたします。




たびたびの質問で恐縮ですが、
もう一つ質問させてください。

　　「プロパティの一覧はどこにあるのでしょうか？」
へのご回答で紹介いただいた
　　「詳細を解説しているサイトを参照する (MDNなど)」
の先
　　　https://developer.mozilla.org/ja/docs/Web/API/Document
　　　https://developer.mozilla.org/ja/docs/Web/API/Element
には

querySelectorAll
も
getElementsByTagName
もあるのですが

uwscrでは
querySelectorAll　はうまく動くのに、　getElementsByTagName　は

　　　[ブラウザ操作エラー] getElementsByTagNameがありません

となります。
　（旧UWSCでは、getElementsByTagName でうまく動いてました。）

どう使い分ければよいのでしょうか？
それとも、UWSCR専用の「エレメントのメソッド一覧」が
どこかのURLにあるのでしょうか？

**Comment by stuncloud** [comment]
> ただ、旧UWSCのプログラムが約300KB(80ファイル)ほどあるので、 
これをできるだけ書き換えせずに chrome で動かしたいのです。

先にもお伝えした通り `createoleobj("InternetExplorer.Application")` で得られる物とBrowserControlは**全くの別物**だということをご理解ください
全くの別物というのは**同じようには動かない**という意味です

> たびたびの質問で恐縮ですが、 もう一つ質問させてください。
> 
> 　　「プロパティの一覧はどこにあるのでしょうか？」 へのご回答で紹介いただいた
 　　「詳細を解説しているサイトを参照する (MDNなど)」 の先
 　　　https://developer.mozilla.org/ja/docs/Web/API/Document
 　　　https://developer.mozilla.org/ja/docs/Web/API/Element には
> 
> querySelectorAll も getElementsByTagName もあるのですが
> 
> uwscrでは querySelectorAll　はうまく動くのに、　getElementsByTagName　は
> 
> 　　　[ブラウザ操作エラー] getElementsByTagNameがありません
> 
> となります。 　

先にお伝えした通りプロパティ(やアトリビュート)はブラウザのものを利用できます
しかし、メソッドに関してはその限りではありません
`querySelectorAll`や`getElementsByTagName`はメソッドでありプロパティではありません

あくまでプロパティに関しての質問であったので回答としては十分であったと思っています
そこに突然メソッドの話をされてこちらも困惑しています

> （旧UWSCでは、getElementsByTagName でうまく動いてました。）

再三お伝えした通り同じものではないので同じようには動きません
**そもそもUWSCにはBrowserControlが存在しないので比較対象にならない**ということをご理解ください

> どう使い分ければよいのでしょうか？ 
それとも、UWSCR専用の「エレメントのメソッド一覧」が 
どこかのURLにあるのでしょうか？

[あります](https://github.com/stuncloud/UWSCR/wiki/%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E6%93%8D%E4%BD%9C#Element%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88)
おっしゃる通りElementオブジェクトは独自のメソッドを持ちます
できればなんですが、機能をご利用になる前にはドキュメントに目を通しておいていただきたいです
(UWSCでヘルプファイルを参照するのが当たり前だったように)

ただし、`0.11.0`にてBrowserControlの大幅な改修を予定していますのでこれらの仕様は大きく変更する可能性があります (破壊的なものもありえます)

**Comment by stuncloud** [comment]
[wikiを更新](https://github.com/stuncloud/UWSCR/wiki/%E3%83%96%E3%83%A9%E3%82%A6%E3%82%B6%E6%93%8D%E4%BD%9C#%E5%B1%9E%E6%80%A7%E5%80%A4%E3%82%84%E3%83%97%E3%83%AD%E3%83%91%E3%83%86%E3%82%A3%E3%81%AE%E5%8F%96%E5%BE%97%E5%A4%89%E6%9B%B4)し、プロパティ及びアトリビュートについての説明を追加しました

![image](https://user-images.githubusercontent.com/2889508/189830891-5aec5194-f6d4-442a-a85f-fd4b8a5b5a4c.png)

**Comment by kawamura1953** [comment]
＞　先にお伝えした通りプロパティ(やアトリビュート)はブラウザのものを利用できます
　　＞　しかし、メソッドに関してはその限りではありません

これを理解していませんでした。
ご説明ありがとうございました。

**Comment by stuncloud** [comment]
@kawamura1953  この質問が解決している場合はクローズしてください
そうでない場合はコメントしてください
