### ISSUE TITLE
未実装か否かの調べ方

### ISSUE THREAD

**Issue by kawamura1953** [stuncloud/UWSCR#58]
いつも初歩的な質問で申し訳ありません。

SENDSTR、CLKITEM、などなどの関数の
実装・未実装は、どうやって調べたらよいのでしょうか？

また、uwsc では動いていた、以下のコードが uwscr ではその次の
エラーメッセージで止まります。"hwnd"は uwsc 特有のものなのでしょうか？

コード
  CLKITEM(hndtoid( g_ie.hwnd ), "タブを閉じる (Ctrl+W)", CLK_ACC)  //現在のタブを閉じる。

メッセージ
850行目:   CLKITEM(hndtoid( g_ie.hwnd ), "タブを閉じる (Ctrl+W)", CLK_ACC)  //現在のタブを閉じる。
[ブラウザ操作エラー] hwndがありません

/////////////////////////////////////////////////////////////////////////
/// いつも気になるのですが、上記のような質問を                  ///
/// この「お問い合わせ　Issue」でしてよいのでしょうか？   ///
/////////////////////////////////////////////////////////////////////////

## 実行環境

- UWSCRバージョン: 0.8.1
- OS: Windows 10

**Comment by stuncloud** [comment]
> SENDSTR、CLKITEM、などなどの関数の
実装・未実装は、どうやって調べたらよいのでしょうか？

実装状況は[リリースページ](https://github.com/stuncloud/UWSCR/releases)で告知しています
また、[wiki](https://github.com/stuncloud/UWSCR/wiki)に記載のある関数が原則実装済みのものとなります

> また、uwsc では動いていた、以下のコードが uwscr ではその次の
> エラーメッセージで止まります。"hwnd"は uwsc 特有のものなのでしょうか？
> 
> コード
CLKITEM(hndtoid( g_ie.hwnd ), "タブを閉じる (Ctrl+W)", CLK_ACC) //現在のタブを閉じる。
> 
> メッセージ
850行目: CLKITEM(hndtoid( g_ie.hwnd ), "タブを閉じる (Ctrl+W)", CLK_ACC) //現在のタブを閉じる。
[ブラウザ操作エラー] hwndがありません

おそらくBrowserControlをご利用中のエラーかと思いますが

> uwsc では動いていた、以下のコード

以前にもお伝えした通り、UWSCにはBrowserControlが存在しないためUWSCで動作していたということはありえません

> "hwnd"は uwsc 特有のものなのでしょうか？

UWSC特有ではありません、というかUWSCは (そしてUWSCRも) 関係ありません
おそらくIEオブジェクトの話をされているのでしょうが、それはあくまでIEの機能の話であり、UWSCはそれを呼び出しているにすぎないからです

> いつも気になるのですが、上記のような質問を
> この「お問い合わせ　Issue」でしてよいのでしょうか？

UWSCRに関する質問であれば問題はありません (そのための場です)

**なのですが**

あなたに関してはどうにも基礎的な知識が足りていなさすぎるという印象を受けます
そのためこちらから伝えたことが理解されていなかったり、同じような質問が繰り返されたりしていると感じています

## BrowserControlについて

再三ご説明しているはずなのですが全く伝わっていないと感じていることをもう一度説明します

**UWSCにおけるIE操作** (`createoleobj("InternetExplorer.Application")`) とは全くの別物です
**UWSCにおけるIE操作** を再現するための機能ではありません
異なる機能なので同じ動きをしないのは **当たり前です**

なのでBrowserControlを利用する限り **UWSCでは〇〇が動いたのですがUWSCRではエラーになります** といった質問がそもそも成り立たないということを理解してください


## 基礎的な知識が足りていないと感じることについて

もう少しDOMやJavaScriptのことを勉強されたほうが良いかと思います
**UWSCにおけるIE操作** でDOMに対して何を行っているか？ということがなんとなくでも理解できていれば、これまでのような質問をされることもなかったと思うんですよね…

**Comment by stuncloud** [comment]
@kawamura1953  この質問が解決している場合はクローズしてください
そうでない場合はコメントしてください
