### ISSUE TITLE
VisualStudioCode上でのステップ実行のデバッグ方法

### ISSUE THREAD

**Issue by 88329** [stuncloud/UWSCR#95]
## 質問
VisualStudioCodeで現在Rust言語で開発を行っています。
ステップ実行でのデバッグを行いたいのですが。
どのような設定作業を行えばできるでしょうか。

当方、Rust言語やVisualStudioCodeでの開発初だった為、
初歩的な質問で恐縮ですがご回答いただけたら幸いです。

**Comment by stuncloud** [comment]
すいません、僕も何をしたかよく覚えてないんですよね
のでぐぐったら以下が出てきました

- https://qiita.com/84zume/items/377033ab6b6aee2a68d7
- https://news.mynavi.jp/techplus/article/c-for-windows-5/

必要なものは開発しているプラットフォームにもよると思いますがWindowsなら上記を参考にすれば良さそうです
pythonはMSストアにありますしね
Windows以外でもVSCodeの拡張を入れる部分は変わらないと思います
なにか不足していてデバッグ実行できない場合でもエラーメッセージになにかしらヒントがあるはずなので、それに応じて環境を整えてください

**Comment by stuncloud** [comment]
どうなったのかわからんけどUWSCRとなんも関係ないのでクローズします

**Comment by 88329** [comment]
連絡遅くなり申し訳ありません。
情報のご提供ありがとうございました。
いただいた情報元になんとか作業を進めることができました。
初歩的な質問に答えていただきありがとうございました。
