### ISSUE TITLE
G_IMG_XとG_IMG_Yについて

### ISSUE THREAD

**Issue by Je1d** [stuncloud/UWSCR#97]
## 要望
G_IMG_X、G_IMG_Yが未実装であれば実装いただきたいです。(認識誤っていましたら申し訳ございません)
補足用コードにconsole出力例記載します。

## 補足用コード
```stylus
C:\hoge\scripts\fugu>UWSCR実行時エラー
huge.uws 9行目: IF CHKIMG("hogahoga.BMP") THEN BTN(LEFT,CLICK,G_IMG_X+2,G_IMG_Y+2)
[評価エラー] 識別子が見つかりません (G_IMG_X)
```

**Comment by stuncloud** [comment]
chkimgはUWSCとは仕様が異なり、戻り値で座標を返します

```stylus
for found in chkimg('hoge.png')
    x = found[0] + 2
    y = found[1] + 2
    btn(LEFT, CLICK, x, y)
next
```

詳しくは以下を参照してください
https://stuncloud.github.io/UWSCR/builtins/window.html#chkimg

ちなみに関数の結果を格納する特殊変数は `G_IMG_*` に限らず廃止し、関数の戻り値で返すような仕様になっています
