### ISSUE TITLE
gettimeで取得している特殊変数が使用できない

### ISSUE THREAD

**Issue by technomodel** [stuncloud/UWSCR#98]
## 概要

gettimeで取得しているはずの G_TIME_* が使えません。

## 再現コード

dt = "2023/04/01 10:10:10"

ts = gettime(, dt)
print ts // 733659010
print format(ts, "%c") // 2023年04月01日 10時10分10秒
print G_TIME_YY //[評価エラー] 識別子が見つかりません (G_TIME_YY)となる

## 実行環境

- UWSCRバージョン: 0.12.1
- OS: Windows (10)

**Comment by stuncloud** [comment]
報告ありがとうございます、以下が原因となります

- `G_TIME_*` がローカルスコープに定数として登録されていたが、ローカルスコープでは定数が検索対象外だったため

0.12.0でModule/Classの処理を修正した際に上記の状態になってしまっていました
以下の修正を行います

- 変数評価の際にローカルスコープの定数も検索対象とする

この修正は次回リリース (0.13.0) で反映予定です
